# Generated by Django 5.1.1 on 2024-10-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='volume_of_all_donations',
            new_name='area',
        ),
    ]
